In [57]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [58]:
from config.database import run_query, save_to_sql

query = "SELECT * FROM transaction_data"

df = run_query(query)

df.head()

,Transaction ID,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN4363205433,ACC83609,ACC14505,4106.87,Deposit,2025-01-01 00:04:49,Success,FALSE,"51.5074 N, 0.1278 W",Mobile,Slice1,89,486,6445
1,TXN3391510523,ACC68952,ACC80170,1977.30,Withdrawal,2025-01-01 00:08:44,Success,FALSE,"34.0522 N, -74.006 W",Desktop,Slice1,64,554,4888
2,TXN6911591624,ACC90406,ACC37430,2256.67,Transfer,2025-01-01 00:12:54,Success,FALSE,"55.7558 N, 37.6173 W",Mobile,Slice3,90,1979,7010
3,TXN4662526045,ACC60425,ACC74426,4636.06,Withdrawal,2025-01-01 00:13:12,Success,FALSE,"51.5074 N, 0.1278 W",Desktop,Slice1,20,1832,3834
4,TXN3490372585,ACC23270,ACC29470,3125.88,Withdrawal,2025-01-01 00:14:29,Success,FALSE,"51.5074 N, 0.1278 W",Mobile,Slice1,41,548,2317

In [59]:
df.describe()

       Transaction Amount  Latency (ms)  Slice Bandwidth (Mbps)      PIN Code
count        14956.000000  14956.000000            14956.000000  14956.000000
mean          2496.139074     76.548944             1531.367679   5467.643354
std           1435.123198     42.094564              851.355028   2596.206133
min             10.290000      5.000000               50.000000   1001.000000
25%           1251.492500     40.000000              794.000000   3210.000000
50%           2494.595000     76.000000             1534.000000   5468.000000
75%           3735.467500    113.000000             2266.250000   7702.000000
max           4999.420000    149.000000             2999.000000   9999.000000

In [60]:
df.describe(include='all')

,Transaction ID,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
count,14956,14956,14956,14956.000000,14956,14956,14956,14956,14956,14956,14956,14956.000000,14956.000000,14956.000000
unique,14956,13762,13783,NaN,3,14940,4,2,6,4,3,NaN,NaN,NaN
top,TXN4363205433,ACC86840,ACC42866,NaN,Transfer,2025-01-04 01:52:18,Success,FALSE,"34.0522 N, -74.006 W",Mobile,Slice2,NaN,NaN,NaN
freq,1,4,4,NaN,5043,2,11937,14160,2528,7542,5031,NaN,NaN,NaN
mean,NaN,NaN,NaN,2496.139074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.548944,1531.367679,5467.643354
std,NaN,NaN,NaN,1435.123198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.094564,851.355028,2596.206133
min,NaN,NaN,NaN,10.290000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,50.000000,1001.000000
25%,NaN,NaN,NaN,1251.492500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,794.000000,3210.000000
50%,NaN,NaN,NaN,2494.595000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.000000,1534.000000,5468.000000
75%,NaN,NaN,NaN,3735.467500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.000000,2266.250000,7702.000000
max,NaN,NaN,NaN,4999.420000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.000000,2999.000000,9999.000000

In [61]:
df.shape

(14956, 14)

In [62]:
df.dtypes

Transaction ID                          str
Sender Account ID                       str
Receiver Account ID                     str
Transaction Amount                  float64
Transaction Type                        str
Timestamp                               str
Transaction Status                      str
Fraud Flag                              str
Geolocation (Latitude/Longitude)        str
Device Used                             str
Network Slice ID                        str
Latency (ms)                          int64
Slice Bandwidth (Mbps)                int64
PIN Code                              int64
dtype: object

In [63]:
df.isnull().sum()

Transaction ID                      0
Sender Account ID                   0
Receiver Account ID                 0
Transaction Amount                  0
Transaction Type                    0
Timestamp                           0
Transaction Status                  0
Fraud Flag                          0
Geolocation (Latitude/Longitude)    0
Device Used                         0
Network Slice ID                    0
Latency (ms)                        0
Slice Bandwidth (Mbps)              0
PIN Code                            0
dtype: int64

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df.columns

Index(['Transaction ID', 'Sender Account ID', 'Receiver Account ID',
       'Transaction Amount', 'Transaction Type', 'Timestamp',
       'Transaction Status', 'Fraud Flag', 'Geolocation (Latitude/Longitude)',
       'Device Used', 'Network Slice ID', 'Latency (ms)',
       'Slice Bandwidth (Mbps)', 'PIN Code'],
      dtype='str')

In [66]:
df["Transaction Type"].unique()

<StringArray>
['Deposit', 'Withdrawal', 'Transfer']
Length: 3, dtype: str

In [67]:
df["Device Used"].unique()

<StringArray>
['Mobile', 'Desktop', 'Deskto', 'Mobil']
Length: 4, dtype: str

In [68]:
df["Fraud Flag"].unique()

<StringArray>
['FALSE', 'TRUE']
Length: 2, dtype: str

In [69]:
df["Transaction Status"].unique()

<StringArray>
['Success', 'Failed', 'Faile', 'Succes']
Length: 4, dtype: str

## DATA CLEANING

In [70]:
df.drop_duplicates(inplace=True)

In [71]:
df.shape

(14956, 14)

In [72]:
df["Device Used"] =  df["Device Used"].replace({"Mobil":"Mobile","Deskto":"Desktop"})

In [73]:
df["Transaction Status"] =  df["Transaction Status"].replace({"Faile":"Failed","Succes":"Success"})

## Rechecking

In [74]:
df["Device Used"].unique()

<StringArray>
['Mobile', 'Desktop']
Length: 2, dtype: str

In [75]:
df["Transaction Status"].unique()

<StringArray>
['Success', 'Failed']
Length: 2, dtype: str

In [76]:
import pandas as pd
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [77]:
df.dtypes

Transaction ID                                 str
Sender Account ID                              str
Receiver Account ID                            str
Transaction Amount                         float64
Transaction Type                               str
Timestamp                           datetime64[us]
Transaction Status                             str
Fraud Flag                                     str
Geolocation (Latitude/Longitude)               str
Device Used                                    str
Network Slice ID                               str
Latency (ms)                                 int64
Slice Bandwidth (Mbps)                       int64
PIN Code                                     int64
dtype: object

In [78]:
df["date"] = df["Timestamp"].dt.date

df["time"] = df["Timestamp"].dt.time

In [79]:
df.head()

,Transaction ID,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code,date,time
0,TXN4363205433,ACC83609,ACC14505,4106.87,Deposit,2025-01-01 00:04:49,Success,FALSE,"51.5074 N, 0.1278 W",Mobile,Slice1,89,486,6445,2025-01-01,00:04:49
1,TXN3391510523,ACC68952,ACC80170,1977.30,Withdrawal,2025-01-01 00:08:44,Success,FALSE,"34.0522 N, -74.006 W",Desktop,Slice1,64,554,4888,2025-01-01,00:08:44
2,TXN6911591624,ACC90406,ACC37430,2256.67,Transfer,2025-01-01 00:12:54,Success,FALSE,"55.7558 N, 37.6173 W",Mobile,Slice3,90,1979,7010,2025-01-01,00:12:54
3,TXN4662526045,ACC60425,ACC74426,4636.06,Withdrawal,2025-01-01 00:13:12,Success,FALSE,"51.5074 N, 0.1278 W",Desktop,Slice1,20,1832,3834,2025-01-01,00:13:12
4,TXN3490372585,ACC23270,ACC29470,3125.88,Withdrawal,2025-01-01 00:14:29,Success,FALSE,"51.5074 N, 0.1278 W",Mobile,Slice1,41,548,2317,2025-01-01,00:14:29

## KPI CALCULATIONS

In [80]:
total_transactions = len(df)

In [81]:
total_transactions

14956

In [82]:
total_amount = df["Transaction Amount"].sum()

In [83]:
total_amount

np.float64(37332255.989999995)

In [84]:
successful_transactions = df[df["Transaction Status"] == "Success"].shape[0]

In [85]:
successful_transactions

11940

In [86]:
failed_transactions = df[df["Transaction Status"] == "Failed"].shape[0]

In [87]:
failed_transactions

3016

In [88]:
success_rate = (successful_transactions / total_transactions) * 100

In [89]:
success_rate

79.83418026210217

In [90]:
fraud_transactions = df[df["Fraud Flag"] == True].shape[0]

In [91]:
fraud_transactions

0

In [92]:
failure_rate = (failed_transactions / total_transactions) * 100

In [93]:
failure_rate

20.165819737897834

In [94]:
average_latency = df["Latency (ms)"].mean()

In [95]:
average_latency

np.float64(76.54894356779887)

In [96]:
average_bandwidth = df["Slice Bandwidth (Mbps)"].mean()

In [97]:
average_bandwidth

np.float64(1531.3676785236694)

### CHART FOR THE DASHBOARD

In [98]:
import plotly.express as px
fig = px.histogram(df, x="Transaction Amount", nbins=50, title="Distribution of Transaction Amounts")
fig.show()

In [99]:
fig = px.pie(df, names="Transaction Status", title="Transaction Status Distribution")
fig.show()

In [100]:
fx = px.box(df,
            x="Transaction Type",
            y="Transaction Amount",
            color="Transaction Type",
            title="Transaction Type Distribution")
fx.show()

In [101]:
transaction_summary = df.groupby("Transaction Type")["Transaction Amount"].sum().reset_index()

fx = px.bar(transaction_summary, x="Transaction Type", y="Transaction Amount", color="Transaction Type", title="Transaction Type Distribution")
fx.show()

In [102]:
daily_df = df.groupby("date")["Transaction ID"].count().reset_index()
daily_df.rename(columns={"Transaction ID": "Total Transactions"}, inplace=True)
fx = px.line(daily_df, x="date", y="Total Transactions", title="Daily Transaction Trend")
fx.show()